# Generated by Django 5.0.14 on 2025-10-01 14:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Floor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                ("width_px", models.PositiveIntegerField(default=1000)),
                ("height_px", models.PositiveIntegerField(default=600)),
            ],
        ),
        migrations.CreateModel(
            name="Box",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("x", models.PositiveIntegerField(default=10)),
                ("y", models.PositiveIntegerField(default=10)),
                ("w", models.PositiveIntegerField(default=120)),
                ("h", models.PositiveIntegerField(default=80)),
                ("color", models.CharField(default="#cde", max_length=16)),
                ("is_visible", models.BooleanField(default=True)),
                (
                    "floor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="boxes",
                        to="datacenter.floor",
                    ),
                ),
            ],
        ),
    ]
