# Generated by Django 5.0.14 on 2025-10-01 15:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("datacenter", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Rack",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("total_units", models.PositiveIntegerField(default=46)),
            ],
        ),
        migrations.AddField(
            model_name="box",
            name="rack",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="box",
                to="datacenter.rack",
            ),
        ),
        migrations.CreateModel(
            name="RackEquipment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("VMware", "VMware"),
                            ("AIX", "AIX"),
                            ("Windows", "Windows"),
                            ("Storage", "Storage"),
                            ("Network", "Network"),
                        ],
                        max_length=20,
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("u_start", models.PositiveIntegerField()),
                ("u_end", models.PositiveIntegerField()),
                (
                    "rack",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="equipment",
                        to="datacenter.rack",
                    ),
                ),
            ],
            options={
                "ordering": ["-u_start"],
            },
        ),
    ]
