# Generated by Django 5.0.14 on 2025-10-01 17:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("datacenter", "0002_rack_box_rack_rackequipment"),
    ]

    operations = [
        migrations.CreateModel(
            name="EquipmentDetail",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "support_contract_supplier",
                    models.CharField(blank=True, max_length=200),
                ),
                ("contract_end_date", models.DateField(blank=True, null=True)),
                (
                    "folder_location_details",
                    models.CharField(blank=True, max_length=500),
                ),
                (
                    "folder_location_pictures",
                    models.CharField(blank=True, max_length=500),
                ),
                (
                    "equipment",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="details",
                        to="datacenter.rackequipment",
                    ),
                ),
            ],
        ),
    ]
